### PR TITLE
Update of dump network and set network 

### PR DESCRIPTION
**Pull request by olmoulin**
Implementation of dumpNetwork and setNetwork using embedded Keras functionalities. The system now saves 2 files for each model, the network architecture as Json file and the model weights as h5 file.
I also added an optional parameter to the dumpNetwork function to indicate if we want to save the NN from the test_policy or train_policy.

### CODE REVIEW

**Comment by VinF** [comment]
Thanks for the commits! To make it also usable for other learning algos than q-learning (e.g. the DDPG or the CRAR one), would it be possible to pass directly the neural networks? For instance in actor-critic there would be two calls to the function with the actor network and the critic network? And it would also avoid needing the argument "train_test". It would be great if it's as modular as possible for the other possible use cases.

**Comment by olmoulin** [comment]
Sure,
Do you want to have an optional parameter where you can pass the NN and if it is not defined it default to the training NN.
When we load it, which NN should we do the same, optional parameter to indicate which NN should be updated and defaulting to update TRAIN and TEST ones ?

**Comment by VinF** [comment]
I'm closing this for now. We can reopen when we have found a solution to the problems that we discussed.

**Comment by olmoulin** [comment]
sure, I need to think a little bit deeper on that :) currently focussed on writing and on the hackathlon (not passionate about it, I was thinking it would be AI related... but now I am part of it I need to work on it ...)

Sent from my iPhone

On 15 May 2021, at 11:03, VinF ***@***.***> wrote:

﻿

I'm closing this for now. We can reopen when we have found a solution to the problems that we discussed.

**Pull request closed without merging**
